### ISSUE TITLE
AttributeError: 'DataManager' object has no attribute '_DataManager__log'

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/e4e-data-management#49]
```
(.venv) (base) PS D:\data\e4e\smartfin\2023-05-17T12_32_VectorNav_Capture> e4edm init_dataset --help
usage: e4edm init_dataset [-h] --date DATE --project PROJECT --location LOCATION [--path DIRECTORY]

optional arguments:
  -h, --help            show this help message and exit
  --date DATE, -d DATE  ISO 8601 Date of expedition (YYYY-MM-DD) or "today"
  --project PROJECT, -p PROJECT
                        Project
  --location LOCATION, -l LOCATION
                        Expedition location (common name)
  --path DIRECTORY      Dataset location, defaults to C:/Users/nthui/AppData/Local/Engineers for
                        Exploration/E4EDataManagement
(.venv) (base) PS D:\data\e4e\smartfin\2023-05-17T12_32_VectorNav_Capture> e4edm init_dataset --date today -p Smartfin -l "ATK2100"
Traceback (most recent call last):
  File "D:\workspace\e4e\e4e_tools\e4e-data-management\.venv\Scripts\e4edm-script.py", line 33, in <module>
    sys.exit(load_entry_point('e4e-data-management', 'console_scripts', 'e4edm')())
  File "d:\workspace\e4e\e4e_tools\e4e-data-management\e4e_data_management\cli.py", line 366, in main
    DataMangerCLI().main()
  File "d:\workspace\e4e\e4e_tools\e4e-data-management\e4e_data_management\cli.py", line 232, in main
    arg_fn(**arg_dict)
  File "d:\workspace\e4e\e4e_tools\e4e-data-management\e4e_data_management\core.py", line 107, in initialize_dataset
    self.save()
  File "d:\workspace\e4e\e4e_tools\e4e-data-management\e4e_data_management\core.py", line 77, in save
    self.__log.debug('Saving')
AttributeError: 'DataManager' object has no attribute '_DataManager__log'
(.venv) (base) PS D:\data\e4e\smartfin\2023-05-17T12_32_VectorNav_Capture> e4edm --version
e4edm 0.0.0.13
(.venv) (base) PS D:\data\e4e\smartfin\2023-05-17T12_32_VectorNav_Capture>
```

**Comment by ntlhui** [comment]
Blocked on #53

**Comment by ntlhui** [comment]
Updated #53
